### ISSUE TITLE
Convert BigFloat to BigUint (from num_bigint)

### ISSUE THREAD

**Issue by Janmajayamall** [stencillogic/astro-float#22] opened 2024-02-28 12:57 UTC
Thanks for the lib! It has been immensely helpful. 

I am running into issues converting a BigFloat instance to BigUint (from [num_bigint](https://docs.rs/num-bigint/latest/num_bigint/struct.BigUint.html)). My naive try is

```rust 
let mut consts = Consts::new().unwrap();

let mut value = BigFloat::from(1.2);

let (sign, radix_repr, ex) = value
  .round(0, ROUNDING_MODE)
  .convert_to_radix(astro_float::Radix::Dec, ROUNDING_MODE, &mut consts)
  .unwrap();
  
// Assume sign is always positive
let value_biguint = BigUint::from_radix_be(&radix_repr, 10).unwrap();
```

I though that  setting to n to 0 (i.e. fractional digits are decimal) will round the value to 1, hence mantissa will 1 and exp will be 0. But this isn't the case. Probably  I am misreding the docs. Can you point me to a function using which I can round the value towards 0 and mantissa will drop rounded-off digits?

**Comment by stencillogic** [comment] 2024-02-28 15:39
`round` is the function that can round fractional part of a number. 
What's the value of this `ROUNDING_MODE` ?

**Comment by stencillogic** [comment] 2024-02-28 15:41
Also, rounding will not change exponent of a number, unless there was overflow during rounding.

**Comment by Janmajayamall** [comment] 2024-02-29 04:18
> What's the value of this ROUNDING_MODE ?

It is set to none - `RoundingMode::None`

**Comment by Janmajayamall** [comment] 2024-02-29 04:23
Ok, so seems a like the only way is to read the mantissa after rounding as a string. Drop off digits after decimal as per the exponent. Then parse the resulting string of digits into BigUint. Do you think there's a better way to do this?

**Comment by Janmajayamall** [comment] 2024-02-29 04:46
This is what I came up with: 

```rust 
let mut consts = Consts::new().unwrap();

let mut value = AstroBFloat::from(1.2);

let (sign, radix_repr, mut ex) = value
    .round(0, ROUNDING_MODE)
    .convert_to_radix(astro_float::Radix::Dec, ROUNDING_MODE, &mut consts)
    .unwrap();

if ex < 0 {
    ex = 0;
}

// Assume sign is always positive
let value_biguint = BigUint::from_radix_be(&radix_repr[..ex as usize], 10).unwrap();
```

**Comment by stencillogic** [comment] 2024-02-29 13:06
`round()` with `RoundingMode::None` has no effect: [docs](https://docs.rs/astro-float/latest/astro_float/enum.RoundingMode.html#variant.None).

The most efficient way in my opinion is to get [raw parts](https://docs.rs/astro-float/latest/astro_float/struct.BigFloat.html#method.as_raw_parts) of big float, and then construct big integer from the mantissa slice after accomplishing required bit shift.

**Comment by Janmajayamall** [comment] 2024-03-06 05:59
Sorry for late reply!

Is this what you had in mind ? 

```rust
// PRECISION = 256
// MANTISSA_LEN = 4
let value = value.0.clone();
let (raw, _, s, _, _) = value.as_raw_parts().unwrap();
let exponent = value.exponent().unwrap();

let mut bits = exponent;
let mut index = MATISSA_LEN - 1;
let mut res = BigInt::zero();
while bits > 0 {
    res += (BigInt::from_u64(raw[index as usize]).unwrap())
        << (astro_float::WORD_BIT_SIZE * index);
    bits -= astro_float::WORD_BIT_SIZE as i32;
    index -= 1;
}
res >>= (PRECISION as i32) - exponent;
res = if s.is_negative() { res.neg() } else { res }
```

**Comment by stencillogic** [comment] 2024-04-12 14:27
Closing the issue as it is not a bug.

**Closed by stencillogic** 2024-04-12 14:27 UTC

**Comment by matthewoestreich** [comment] 2026-04-11 07:20
Putting this here in case it helps someone..

```rust
fn bigfloat_to_bigint(
    mantissa_limbs: &[u64],
    exponent: i32,
    precision: usize,
    sign: astro_float::Sign,
) -> BigInt {
    let mut bi = BigInt::from(0i32);
    for (i, &limb) in mantissa_limbs.iter().enumerate() {
        bi += BigInt::from(limb) << (i * 64);
    }
    let p = precision as i32;
    if exponent >= p {
        bi <<= exponent - p;
    } else {
        bi >>= p - exponent;
    }
    if sign == Sign::Neg { -bi } else { bi }
}

let integer_part = "123456789123456789123456789123456789123456789";

let bf = format!("{integer_part}.123456789")
    .parse::<BigFloat>()
    .unwrap();

let (mantissa, precision, sign, exponent, _) = bf.as_raw_parts().unwrap();

let bi = bigfloat_to_bigint(mantissa, exponent, precision, sign);

assert_eq!(integer_part, bi.to_string());
```
